FROM openjdk:17-jdk-slim AS build
WORKDIR /app

COPY gradlew .
COPY gradle/ gradle/
RUN chmod +x gradlew
COPY . .

RUN ./gradlew clean build -x test --no-daemon

FROM openjdk:17-jdk-slim
WORKDIR /app

COPY --from=build /app/build/libs/eureka-server-0.0.1-SNAPSHOT.jar eureka-server.jar

ENTRYPOINT ["java", "-jar", "eureka-server.jar"]