FROM openjdk:17-jdk-slim AS build
WORKDIR /app

COPY gradlew .
COPY gradle/ gradle/
RUN chmod +x gradlew
COPY . .

RUN ./gradlew clean build -x test --no-daemon

FROM openjdk:17-jdk-slim
WORKDIR /app

COPY --from=build /app/build/libs/slack-service-0.0.1-SNAPSHOT.jar slack-service.jar

ENTRYPOINT ["java", "-jar", "slack-service.jar"]